services:
  - type: web
    name: flexipdf
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://flexipdf-9frt.onrender.com
      - key: NODE_VERSION
        value: 20.14.0
    autoDeploy: true 