services:
  - type: web
    name: flexipdf
    runtime: node
    plan: free
    buildCommand: |
      cd server && npm install
      cd ../client && npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://flexipdf.onrender.com
      - key: NODE_VERSION
        value: 20.14.0
    autoDeploy: true 